### PR TITLE
Compile Scala 3 version with Scala LTS (3.3.4)

### PR DESCRIPTION
**Pull request by Dichotomia**
Compile Scala 3 version with Scala LTS (3.3.4). See issue https://github.com/pac4j/play-pac4j/issues/731

### CODE REVIEW

**Comment by leleuj** [comment]
Copy that. Thanks

**Comment by Dichotomia** [comment]
Thanks you for merging this.
Do you think that would be possible to publish a release?
The last patch is unusable within a Scala 3 application for this reason.

**Comment by Dichotomia** [comment]
[error] error while loading scala,
[error] TASTy file scala/NamedTupleDecomposition.tasty could not be read, failing with:
[error]   Forward incompatible TASTy file has version 28.6, produced by Scala 3.6.1-bin-nonbootstrapped,
[error]   expected stable TASTy from 28.0 to 28.5.
[error]   To read this TASTy file, use a newer version of this tool compatible with TASTy 28.6.
[error]   Please refer to the documentation for information on TASTy versioning:
[error]   https://docs.scala-lang.org/scala3/reference/language-versions/binary-compatibility.html

**Comment by leleuj** [comment]
Sure. I just cut the v12.0.2-PLAY3.0 release. It will show up in the Maven central repo within a few hours/minutes.

**Pull request merged**
