### PR TITLE
Preliminary support for Play 2.7

### PR DESCRIPTION
**Pull request by mellster2012**
Adds preliminary support for Play 2.7 until Deadbolt and the Play Java API access has been refactored.

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for your contribution. It will go in a new v8 version. Ping me when it's ready.

**Comment by mellster2012** [comment]
@leleuj  This should be ready to go - I wanted to keep deadbolt scala and java version in sync so I used the current latest scala version of 2.6.1 for the preliminary play 2.7 support. We can attempt partial deadbolt upgrades in separate PRs.

**Comment by leleuj** [comment]
I created the 7.0.x branches. So can you upgrade the version to 8.0.0-SNAPSHOT in your PR? Can you also submit PRs for the demos: https://github.com/pac4j/play-pac4j-java-demo and https://github.com/pac4j/play-pac4j-scala-demo? Thanks

**Comment by taggiasco** [comment]
Hi @mellster2012 @leleuj 
Any news about this PR ? Or may I help in any way ?

**Comment by leleuj** [comment]
Sure. The PR must be upgraded to version 8 and PRs must be submitted for the demos.

**Comment by mellster2012** [comment]
Let me get back to it - I should have same time this week.

**Comment by mellster2012** [comment]
@leleuj @taggiasco PR updated and PRs for java and scala demos submitted. Upgraded to play 2.7.2.

**Comment by leleuj** [comment]
Thanks

**Comment by vidma** [comment]
@leleuj do you know how stable is new play 2.7 support already and what's missing if any? at the moment we care only about LDAP + SAML.

when do you plan to release play-pac4j `8.0.0` with play 2.7 support?

**Comment by vidma** [comment]
@mellster2012 @taggiasco

**Comment by leleuj** [comment]
I haven't made any test so far. It could after the pac4j v3.7.0 release (end-May).

**Comment by mellster2012** [comment]
@vidma we have been using it in production, oidc and saml.

**Comment by leleuj** [comment]
Good news!

**Pull request merged**
