### PR TITLE
dependencies: downgrade Guice to version that Play 2.9/3.0 uses

### PR DESCRIPTION
**Pull request by ahjohannessen**
@leleuj Is it possible to fixate renovate bot to be on Guice v6.0.0 - Play 2.9 / 3.0 use 6.0.0 and fail with version 7.

### CODE REVIEW

**Comment by leleuj** [comment]
Yes, I thought I had already reverted Guice to v6.

**Comment by ahjohannessen** [comment]
Great :) Any chance of getting a 12.0.0-PLAY3.0 now that pac4j 6.0.0 is released?

**Comment by ahjohannessen** [comment]
@leleuj Probably also a 12.0.0-PLAY2.9 for those that use Play 2.9 :)

**Comment by leleuj** [comment]
Sure. I will do that very soon (likely tomorrow)...

**Comment by ahjohannessen** [comment]
Great 👍

**Comment by leleuj** [comment]
I just cut the releases. They will show up soon in the Maven central repo.

**Comment by ahjohannessen** [comment]
Super, thanks a lot 👍

**Pull request merged**
