### PR TITLE
all: Play 2.9 + Scala 3 support

### PR DESCRIPTION
**Pull request by ahjohannessen**
Not ready for merging, but rather preparation for Play 2.9.0 final and Scala 3

@leleuj WDYT? :)

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for your contribution.

This targets the master and while it is logical, I don't think this is not enough currently.
OpenSAML v5 won't be released before the end of the year and so is pac4j v6 and play-pac4j v12.

So in addition to this PR, you should start another PR based on the branch 11.1.x-PLAY2.8 for a new version 11.1.x_PLAY2.9...

**Comment by ahjohannessen** [comment]
@leleuj I will do that.

I wonder, is it possible to get a 12.0.0-PLAY2.8-RC1 version such that one does not need depend on 12.0.0-SNAPSHOT?

**Comment by leleuj** [comment]
I just cut the v12.0.0-PLAY.2.8-RC1 release. It will show up in the Maven repo within a few minutes/hours.

**Comment by ahjohannessen** [comment]
@leleuj Thank you very much 👍 :)

**Comment by ahjohannessen** [comment]
Closing this as I have more recent work [here](https://github.com/pac4j/play-pac4j/compare/master...ahjohannessen:play-pac4j:play-pac4j-parent-12.0.0-PLAY2.9-RC2)

**Pull request closed without merging**
