### PR TITLE
Revamped Scala implementation of Security trait

### PR DESCRIPTION
**Pull request by KarelCemus**
Limitations of the current version:

- `Secure` enforced `AnyContent`, which makes smooth integration with other actions very difficult (or I'm missing something)
- `Secure` expected `List[P] => Action` instead of just an action, which limits action composition. Instead, I introduced `SecureAction` action builder, which uses `AuthenticatedRequest` containing the identities and does not limit action composition at all.

New Features:
- `Secure` is no longer a function, it's an object extending `ActionBuilder`. This eases its use and follows Play 2.6 guide
- Introduced `AuthenticatedRequest` extending `Request` and encapsulating the profiles and the nested `Request`. This substitutes the original `List[P]=>Action[A]`.
- introduced function `profiles` expecting implicit `AuthenticatedRequest` to ease migration to `5.0.x`
- To ease injection of dependencies, Play uses `ControllerComponents`. I introduced `SecurityComponents` extending `ControllerComponents` and adding all dependencies required by `Security` trait to reduce the number of dependencies to just one.
- The logic itself is unchanged.

Limitations of the new version:

- There are breaking changes in the inheritance, though you propose a version `5.0.x`, which allows some breaking changes, I hope.
- the actual use of `Secure` should not introduce many breaking changes except for the removal of `List[P]=>Action[A]`

Besides this PR, there is also pending PR on scala demo to show the migration

### CODE REVIEW

**Comment by leleuj** [comment]
This looks really good to me (I focused myself on the demo).

Can you update the README and  especially the "Migration guide" section before I merge these changes? Thanks

**Comment by leleuj** [comment]
@KarelCemus any update on this?

**Comment by KarelCemus** [comment]
Sorry, I'm busy these days. Maybe I'll get to this around or at the weekend.

**Comment by leleuj** [comment]
OK. No problem, I just wanted to be sure you got my previous message.

**Comment by leleuj** [comment]
@KarelCemus any update on this?

**Comment by KarelCemus** [comment]
What about this, does it work for you or is there anything to adjust?

**Comment by leleuj** [comment]
I think we're almost good at the documentation level. The "User profile" section should be updated for the Scala support: https://github.com/pac4j/play-pac4j#5-get-the-user-profile-profilemanager

**Comment by KarelCemus** [comment]
Better? Or is there still anything to adjust?

**Comment by leleuj** [comment]
Looks good. Thanks. Merging...

**Comment by KarelCemus** [comment]
Great, thanks. Is there any release schedule?

**Comment by leleuj** [comment]
Not really, it will depend on the release of pac4j v3...

**Comment by KarelCemus** [comment]
So it won't be likely released soon? Could you then release at least a milestone, please? I need to use it in a release of a commercial product and I cannot reference a snapshot.

Thanks!

**Comment by leleuj** [comment]
OK. I keep that in mind, I will try to release a RC1 in the next few weeks...

**Pull request merged**
