### PR TITLE
update to 4.0.0-RC2-SNAPSHOT

### PR DESCRIPTION
**Pull request by SoerenSilkjaer**

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for the PR. I'll take a closer look at it when I work on upgrading play-pac4j to pac4j v4...

**Comment by SoerenSilkjaer** [comment]
I have been running this build in one of our systems for over 3 months now, no issues so far.

**Comment by leleuj** [comment]
This is an excellent contribution. Merging...

**Comment by leleuj** [comment]
Set version to 9.0.0-RC3-SNAPSHOT based on pac4j v4.0.0-RC3-SNAPSHOT...

**Comment by SoerenSilkjaer** [comment]
When will pac4j v4.0.0-RC3-SNAPSHOT be released?

**Comment by leleuj** [comment]
As soon as play-pac4j v9.0.0-RC3 will be ready: it means finishing the pac4j v4 upgrade, upgrading dependencies, Scala 2.13, finishing the Play 2.7 upgrade...

**Comment by leleuj** [comment]
play-pac4j v9 and the demos have been upgraded to pac4j v4. Several issues remain on the Scala demo I'll address later on...

**Comment by SoerenSilkjaer** [comment]
> play-pac4j v9 and the demos have been upgraded to pac4j v4. Several issues remain on the Scala demo I'll address later on...

Okay. We should let the others know here:

https://github.com/pac4j/play-pac4j/issues/265

**Pull request merged**
