### PR TITLE
Alternate threadpool

### PR DESCRIPTION
**Pull request by entropicdrifter**
This is my alternative solution to #182 
I've tested this against the current solution using the methods described by @leleuj in #194 and found it to be anywhere from 40%-140% (on average ~50%) faster after manually tuning the threadpool. Please benchmark this to confirm my results, as the requests/second numbers I was getting on my laptop were quite a bit lower than those mentioned in #194 for both the current master and this version, either due to changes in the randomized blocking times or due to hardware specs.

Notes:

You have to add the threadpool configuration to application.conf.
For example, I've found the best results with:
```
pac4j-threadpool{
	type = Dispatcher
	executor = "thread-pool-executor"
	thread-pool-executor {
    	core-pool-size-min = 64
    	core-pool-size-factor = 8
    	core-pool-size-max = 256
  	}
  	throughput = 1
}
```

But this was tuned to my laptop (4 cores, so size factor is set to cores * parallelism, thus 8 in my case), so feel free to tinker with those settings for varying results.

If this method is found to be acceptable, I would be happy to change the README to reflect the additional needed configuration.

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for giving it a try. I'll run new benchmarks soon to see if I can reproduce the improvements.

**Comment by leleuj** [comment]
I have made several benchmarks with different settings for the pool, but I still have slightly better results with the current solution than with your proposal.

@taggiasco would mind running some benchmarks as well? Thanks

**Comment by taggiasco** [comment]
Hi @leleuj 
Well, I don't know how to do these benchmarks.

**Comment by leleuj** [comment]
Fairly simple: just patch the source code with this PR and use one of the demos (Java or Scala) by adding the previous thread-pool configuration.

Then, run some ab testing on the appropriate URL. Example: `ab -c 15 -n 10000 http://localhost:9000/dba/index.html?username=x&password=y` (15 concurrent threads, 10000 requests)

**Comment by leleuj** [comment]
I plan to release play-pac4j v4.0.0 soon, it's been long-awaited, we'll add that in the next major version (5.0) if ever it proves to be relevant...

@gmethvin @vidma @hugovalk Having some time to run some benchmarks between the current implementation and this proposal?

**Comment by leleuj** [comment]
Closing this old proposal

**Pull request closed without merging**
