### PR TITLE
Authentication exception were not logged.

### PR DESCRIPTION
**Pull request by hugovalk**
Small fix to the security filters, to actually log exceptions.

### CODE REVIEW

**Comment by leleuj** [comment]
We now have many tests provided by the DevFactory guys and the build is broken on one of them: can you check that? Thanks

**Comment by hugovalk** [comment]
This test has nothing to do with my change. When I run the failing test multiple times, it fails now and then, so it is unstable.

**Comment by leleuj** [comment]
OK. If it's not a good test, can you remove it by the way?

**Comment by leleuj** [comment]
Thanks

**Pull request merged**
