### PR TITLE
Updated pom.xml, retrieve SecurityLogic implementation from Config ob…

### PR DESCRIPTION
**Pull request by richard77**
Added support of injecting custom SecurityLogic implementation in Config object.
This allows SecureAction to retrieve the value from the Config object instead having it hard-coded into the class or adjusted at Runtime.

### CODE REVIEW

**Comment by leleuj** [comment]
It should work, though I've been thinking a little more on this.

What goes in the `Config` object are the common components used by all *pac4j* implementations. At the same time, we always prioritize framework mechanisms over *pac4j* generic mechanisms.

So in Play, the `SessionStore` is not defined in the *pac4j* way, but rather in the Play way: using dependency injection rather than the `Config` component.

I think we should do the same for the `securityLogic`: inject a specific one via dependency injection (and have a default one though) rather than define it at the `Config` level. Does it make sense?

**Comment by richard77** [comment]
The reasoning is fine and I agree. 
But as the ```SecurityLogic``` and the ```DefaultSecurityLogic``` classes are part of the pac4j-core module it shouldn't they be part of the Config object?

**Comment by leleuj** [comment]
In all implementations, setters (on filters) are used to define new logics. Play is the only one to make it impossible because of the annotation way.
So for now, it's not necessary to have the logics as a central configuration, but this can change if we have new *pac4j* implementations.

So we only need a solution for Play and I think the best one is dependency injection.

**Comment by richard77** [comment]
Ok, i've reverted the Config object changes and closed the PR for pac4j. 
I'm adding a binding for the SecurityLogic. 
I cannot add a default binding ```@implementedBy``` as this is only allowed on the ```SecurityLogic``` interface (afaik), so in the module we will always need to bind the SecurityLogic to the DefaultSecurityLogic (or own implementation).
The ```SecureAction``` receives the bound implementation through its constructor.

**Comment by leleuj** [comment]
The `SecurityLogic` is a very low-level component people don't need to know generally. We should really have a default implementation: cannot the injection be optional?

I've seen: `@Inject @Nullable` and `@Inject(optional = true)`: can it do the job?

**Comment by richard77** [comment]
We've just pushed changes to the project into the PR.
The ```@Secure``` annotation works, but we could not get the Scala side working correctly. Mainly the injection of the SecurityLogic implementation in ```SecurityFilter.scala``` and ```Security.scala```. Hope you can be of assistance there.

**Comment by leleuj** [comment]
I see already committed changes in this PR, but anyway, I will take a look at how to handle optional injection, I'd like to avoid direct Guice usage.

**Comment by richard77** [comment]
Forgive me if I did something that is not the 'normal' workflow with github. I'm new to this approach. 

Anyway, I've tried the ```javax.annotation.Nullable``` annotation over the google Guice ```@Inject``` but that did not work. Guice kept complaining the variable was not bound. Eventually I got the injection to work correctly with ```@Secure```. 

Using the ```SecurityFilter``` requires the custom ```SecurityLogic``` to be injected in the scala classes as well. But Guice wouldn't let me inject it correctly.

Hope this explanation helps..

**Comment by leleuj** [comment]
No problem. I don't think I'll be more successful than you, but I'll give a try. At worst, we'll move back to your original proposal.

**Comment by leleuj** [comment]
@richard77 :

Using `@Inject` in the `SecureAction` with an already default value makes it optional while this doesn't work in the `SecurityFilter` in Scala. Exactly your conclusion.

Anyway, can we go back to your original proposal (sorry for the waste of time): can you reopen the PR on pac4j? And reset this PR or create a new one (I think it would be better)? Thanks

**Comment by richard77** [comment]
Closing this PR as requested. Reverting back to old sollution

**Pull request closed without merging**
