### PR TITLE
all: Play 2.9.0 / add Scala 3 / drop Scala 2.12

### PR DESCRIPTION
**Pull request by ahjohannessen**
- add support for Play 2.9.0
 - add support for Scala 3
 - drop support for Scala 2.12 as Play 2.9.0 does not support Scala 2.12
 - adjust web context and security wrt. changes in play 2.9.0
 - upgrade various dependencies
 - downgrade guice / scalatest as Play uses those.

 See: https://github.com/playframework/playframework/commit/b5ef04a6beb34c903984b3859da20a2df23a9f59

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@leleuj Play 2.9 is final - Here is a PR to moving play-pac4j to that :)

**Comment by leleuj** [comment]
Thanks for your contribution.

I just made a few adjustments:
- the existing `master` is moved to a new `12.0.x-PLAY2.8` branch
- the version is set to `12.0.0-PLAY2.9-SNAPSHOT`
- the `pac4j` version is set to `6.0.0-RC10-SNAPSHOT` and the `jackson-databind` library is excluded
- the `PlayWebContext` is complemented
- the README is complemented as well

**Comment by ahjohannessen** [comment]
@leleuj Thanks :) When do you plan on releasing 12.0.0-PLAY2.9? When `pac4j` v6.0.0 is released?

**Comment by leleuj** [comment]
I'm not sure yet. Likely before the end of November.

**Comment by ahjohannessen** [comment]
Ok 👍

**Comment by mkurz** [comment]
@leleuj Would it be possible to also start creating actual GitHub releases? People can follow this repository and get notified when a new release got published. You just need to draft and then publish a new release here: https://github.com/pac4j/play-pac4j/releases/new To make things easy you can try the "Generate release notes" button :wink:

**Comment by leleuj** [comment]
I'll give it a try, but we already have the release notes: https://github.com/pac4j/play-pac4j/wiki/Release-notes

**Comment by mkurz** [comment]
@leleuj ah ok. You could just reference to that page. nothing else. I think that would be ok, just to get people notified.

**Comment by leleuj** [comment]
OK. I just did it: https://github.com/pac4j/play-pac4j/releases

**Pull request merged**
