### PR TITLE
Update Play 2.6

### PR DESCRIPTION
**Pull request by taggiasco**
Update of Play version from 2.5 to 2.6.

### CODE REVIEW

**Comment by leleuj** [comment]
Great!

But the build is broken due to test failures.

I was expecting some changes in the `PlayWebContext` as the request attributes should not be handled in the tags anymore: https://www.playframework.com/documentation/2.6.x/Migration26#Request-attributes

**Comment by taggiasco** [comment]
Hi Jérôme,
Now it's ok.
However, Deadbolt 2 has not been carried to Play 2.6. So I'm really not sure how it would work actually.
I'm questioning about Play 2.6, and I'll keep you update about that.
Best regards

**Comment by taggiasco** [comment]
Hi Jérôme,
I just see one usage of the tag feature. In the SecurityFilter (Scala part). It's easy to change. However, do you know where the tag is read ? Because I don't find this.
Thanks,
Matt

**Comment by leleuj** [comment]
It's very tricky.

In the `SecurityFilter`, we get the profiles, serialize them and pass them as a tag in Scala, which becomes available in the args in the Java context and is read by: https://github.com/pac4j/play-pac4j/blob/master/src/main/java/org/pac4j/play/PlayWebContext.java#L190

I'm not sure if this is still useful for Play 2.6...

**Comment by taggiasco** [comment]
Ok I see.
However, in the PlayWebContext, the fonction is getRequestAttribute which should be equivalent to setRequestAttribute. I don't understand why setRequestAttribute puts an an attribute in the arguments of the context, whereas getRequestAttribute should now read something from the attributes of the request.
Moreover, in the SecurityFilter, the profiles are read from the arguments of the javaContext.
Well I'm sorry but it's not clear to me.

**Comment by leleuj** [comment]
Yes, as I said, it's tricky. It's a matter of passing data between the Java context and the Scala context.

When the Java context is created, the args come from the Scala tags. In `JavaHelpers`:

```scala
  /**
   * Creates a java context from a scala Request[RequestBody]
   * @param req
   */
  def createJavaContext(req: Request[RequestBody]): JContext = {
    new JContext(
      req.id,
      req,
      new JRequestImpl(req),
      req.session.data.asJava,
      req.flash.data.asJava,
      req.tags.mapValues(_.asInstanceOf[AnyRef]).asJava)
  }
```

Most classes in play-pac4j are Java ones and use the Java context, except the `SecurityFilter`. So when the `SecurityFilter` is triggered, it uses the Java context and gets the user profiles from the `USER_PROFILES` arg.
It is then serialized and passed as a tag.
Next in the request processing, when the `ProfileManager` or another pac4j object is used, it leverages on the Java context where the `USER_PROFILES` arg is the serialization of the user profiles. Thus, the specific logic in the `getRequestAttribute` of the `PlayWebContext`.

**Comment by laco** [comment]
We're desperately waiting for this merge. Is there anything I can help?

**Comment by leleuj** [comment]
I didn't feel in a hurry as we're still on RC1 for Play 2.6.

That said, I think the PR is ready for merge so if @taggiasco is in line, I can merge it (play-pac4j v4 based on Play 2.6).

**Comment by taggiasco** [comment]
Hi,
In fact Play 2.6 has been released last Friday. I will update the PR tomorrow if it's ok for you.

**Comment by leleuj** [comment]
Thanks. Let's merge it then...

**Comment by leleuj** [comment]
@taggiasco can you submit PR to upgrade the demos as well? Thanks

**Comment by laco** [comment]
Thank you guys!

**Pull request merged**
