### PR TITLE
Put the current profile to the Http.Context for template access

### PR DESCRIPTION
**Pull request by tuxBurner**
Since CDI it is not possible to access the userprofile in a template directly because you need stuff which is handled via injection.

I worte this annotation which puts if avaible the userprofile into the Http.Context so you can access it from a template.

### CODE REVIEW

**Comment by tuxBurner** [comment]
I added a sample in play-java-demo see pull request: https://github.com/pac4j/play-pac4j-java-demo/pull/40

**Comment by leleuj** [comment]
OK. I see your point and that's a good idea.

That said, starting to review your PR, I realized it should already work.

After a successful authentication, the map of profiles is saved as a request attributes (https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/ProfileManager.java#L113) and thus in the context (https://github.com/pac4j/play-pac4j/blob/master/src/main/java/org/pac4j/play/PlayWebContext.java#L213).

Though, when going through the `SecurityFilter`, the profiles are serialized. Yes, I know, it's a bit hacky ;-)

So you should have the access to the profiles (in a serialized format or not) from the context.

Thus, with the `ProfileHelper.flatIntoOneProfile` method, you could certainly create a static `Optional<CommonProfile> getProfile(ctx)` method in the `PlayWebContext`. It's just an example, you can have a better proposal...

**Comment by tuxBurner** [comment]
Ah  nice one okay than we dont need the duplicated code so i will try your approach.

**Comment by leleuj** [comment]
Any update on this?

**Comment by tuxBurner** [comment]
Hi @leleuj looked at it and do i understand this correctly that i need to configure the security filter for this ?

**Comment by leleuj** [comment]
Yes, the user profile is populated via the `SecurityFilter` / `Secure` annotation/function.

**Comment by leleuj** [comment]
Closing for now. Feel free to reopen with your proposal.

**Pull request closed without merging**
