### PR TITLE
get location form the play context, update play version

### PR DESCRIPTION
**Pull request by andriykuba**
The `java.lang.NullPointerException` exception is throwing starting from the **Play 2.5.3**. 

So I update the play version. 

It is workable for **Play 2.5.0**, **Play 2.5.1** and **Play 2.5.2** as well.

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for the fix and the updates of the demos. I'll port that to the master as well.

I'll re-test the demos and release the 2.2.0 version.

**Comment by leleuj** [comment]
I have some trouble with the SAML support. I will investigate...

**Comment by andriykuba** [comment]
Hello, @leleuj, three things:

1. The reason of problem with **SAML** is the **SBT** version. **Play 2.5** recommends to use **SBT 0.13.11**, and it seems like this version does not include `.xml` files from the `conf` directory into the classpath by default. 
I run **play-pac4j-java-demo** with the **SBT 0.13.8** - **SAML** works. 
My suggestion is to add a script to the `build.sbt` to copy all that we need for **SAML** into the classpath on a build.  It would be nice to have a subfolder in `conf` for **SAML** like `conf\saml\`

2. I forgot to update all modules to **1.8.8** from **1.8.6** in the demos, so I will do this and will send pull requests. Sorry about that. 

3. Minor change in the `application.conf` of demos must be done as well. The `play.i18n.langs` must be a  list in **Play 2.5**. There is no error if you run in development mode, but I got it when tried to deploy demo: `play.i18n.langs has type STRING rather than LIST`. I will fix it with the point 2 of this list.

**Comment by andriykuba** [comment]
Hello @leleuj, I fixed it. Look on my pull request, please.

**Comment by leleuj** [comment]
I just merged your three PR: I will re-test everything and release as soon as possible...

**Comment by leleuj** [comment]
@andriykuba : I re-tested both demos (Java and Scala, 2.2.x branches) and I have two issues with the Scala demo:
1) there is no DEBUG logs, although the logback configuration seems correct
2) the "Protected url by OpenID Connect" link returns an "Internal Error" without any error log.

Can you take a look at it? Thanks

**Comment by andriykuba** [comment]
Hi, @leleuj, I verifyed https://github.com/pac4j/play-pac4j-scala-demo and I did not see the issues you had described. I had been used sonatype snapshot repository for resolving **pac4j-play**.  

1) The logs looks like 

```
[debug] - org.pac4j.play.java.RequiresAuthenticationAction - url: http://localhost:9000/facebookadmin/index.html
[debug] - org.pac4j.play.java.RequiresAuthenticationAction - clientName: FacebookClient
[debug] - org.pac4j.play.java.RequiresAuthenticationAction - currentClients: [<FacebookClient> | name: FacebookClient |]
[debug] - org.pac4j.play.java.RequiresAuthenticationAction - useSession: true
[debug] - org.pac4j.play.store.PlayCacheStore - generated sessionId: bcd94a1e-b4a8-4130-b072-559440333236
[debug] - org.pac4j.play.java.RequiresAuthenticationAction - profile: null
[debug] - org.pac4j.play.java.RequiresAuthenticationAction - Starting authentication
[debug] - org.pac4j.play.java.RequiresAuthenticationAction - requestedUrl: http://localhost:9000/facebookadmin/index.html
```

2) The "Protected url by OpenID Connect" link opens the page with my google accounts list.

Maybe you have the old verison of the **pac4j-play** cashed locally. I got similar situation when build **pac4j-play** locally. So I manually delete the `~/.ivy2/cache/org.pac4` folder.

**Comment by leleuj** [comment]
Indeed, it works now. Starting the release...

**Comment by leleuj** [comment]
The play-pac4j v2.2.0 release should be available in the Maven central repository in a few hours...

**Pull request merged**
