### PR TITLE
Revert "PlayCookieStore"

### PR DESCRIPTION
**Pull request by leleuj**
Reverts pac4j/play-pac4j#166

### CODE REVIEW

**Comment by leleuj** [comment]
@entropicdrifter Reverting to cut the release

**Comment by dbhatte** [comment]
Any specific reason for reverting PlayCookieStore?

**Comment by leleuj** [comment]
Sure. The PlayCookieStore was not fully working. See:
https://github.com/pac4j/play-pac4j/issues/167

**Comment by vidma** [comment]
@leleuj what are the issues and what work is needed to get it working? I might contribute a bit on this one.

**Comment by leleuj** [comment]
Currently, the `PlayCacheSessionStore` stores an identifier in the Play session and the whole user profile in the Play cache.
The idea behind this `PlayCookieStore` is to save the whole user profile (in fact, the user profileS) in the Play session cookie, which requires to encrypt data to protect them from disclosure. That's why there is an `EncryptionConfiguration` in the constructor.

I don't remember all discussions, but I think the proposed solution was almost working. You should copy/paste the source code and see if it works and fix issues if ever there are. The use of the `clearSensitiveData` method should likely be optional, but was used by default to limit the size of the profiles.

**Pull request merged**
